AWSTemplateFormatVersion: 2010-09-09
Resources:
  CSPMManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: Policy for reader role
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - "ecr:BatchGetImage"
Outputs:
  PolicyArn:
    Value: !GetAtt CSPMManagedPolicy.PolicyArn
